name: Deploy

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

env:
  dotnet-version: "6.0"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore src/WebUI
    - name: Build
      run: dotnet publish src/WebUI --packages ./.nuget --configuration Release
    - name: Upload MemberManager Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: membermanager-build
        path: |
          src/WebUI/bin/Release/net${{ env.dotnet-version }}/publish/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        if_key_exists: replace
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.CAMPUS_CONSULT_SERVER_IP }} >> ~/.ssh/known_hosts
    - name: Download MemberManager Build Artifact
      uses: actions/download-artifact@master
      with:
        name: membermanager-build
        path: |
          build
    - name: Set executable permission
      run: chmod +x ./build/MemberManager.WebUI
    - name: Deploy with rsync
      run: rsync -avz ./build/ ${{ secrets.CAMPUS_CONSULT_SERVER_USER }}@${{ secrets.CAMPUS_CONSULT_SERVER_IP }}:/var/www/membermanager/publish/
    - name: Restart backend
      run: ssh ${{ secrets.CAMPUS_CONSULT_SERVER_USER }}@${{ secrets.CAMPUS_CONSULT_SERVER_IP }} 'source $HOME/.nvm/nvm.sh && pm2 restart MemberManager'
