name: .NET Core

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
    - name: Install dependencies
      run: dotnet restore src/WebUI
    - name: Build
      run: dotnet build --configuration Release --no-restore src/WebUI
    - name: Test
      run: dotnet test --verbosity normal tests/Applicaton.IntegrationTests
    - name: Check Format
      run: cd src/WebUI/ClientApp && npm ci && npm run format:check
